[build]
  publish = "."

[[redirects]]
  from = "/beats"
  to = "/beats/"
  status = 301

[[headers]]
  for = "/beats/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/beats"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/inprogress/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/investors/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/investors"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"
