[build]
  publish = "."

[[redirects]]
  from = "/investors"
  to = "https://petproxy.biz"
  status = 301
  force = true

[[redirects]]
  from = "/investors/*"
  to = "https://petproxy.biz"
  status = 301
  force = true

[[redirects]]
  from = "/beats"
  to = "/tom/"
  status = 301
  force = true

[[redirects]]
  from = "/beats/"
  to = "/tom/"
  status = 301
  force = true

[[redirects]]
  from = "/tom"
  to = "/tom/"
  status = 301

[[redirects]]
  from = "/adam"
  to = "/adam/"
  status = 301

[[redirects]]
  from = "/ab"
  to = "/ab/"
  status = 301

[[headers]]
  for = "/beats/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/beats"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/tom/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/tom"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/adam/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/adam"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/inprogress/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/ab/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/ab"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/investors/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/investors"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"
